_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: electricity_eval
  offset: 18412 # Same as _lsf_dataset.py
  eval_length: 2630 # Same as _lsf_dataset.py, test_length=5260
  prediction_lengths: [96, 192, 336, 720]
  context_lengths: [1000, 2000, 3000, 4000, 5000]
  patch_sizes: [32, 64]  # freq='h'