_target_: uni2ts.data.builder.simple.generate_eval_builder
dataset: ETTh2_eval
offset: 8640  # Same as _lsf_dataset.py
eval_length: 2880  # Same as _lsf_dataset.py
prediction_length: ???
context_length: ???
patch_size: ???
mode: ???
distance: 1