_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: weather_eval
  offset: 36887 # Same as _lsf_dataset.py
  eval_length: 5269 # Same as _lsf_dataset.py; test_length=10539
  prediction_lengths: [96, 192, 336, 720]
  context_lengths: [1000, 2000, 3000, 4000, 5000]
  patch_sizes: [32, 64, 128]  # freq='10T'