_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
checkpoint_path:
  _target_: huggingface_hub.hf_hub_download
  repo_id: Salesforce/moirai-1.0-R-base
  filename: model.ckpt
num_samples: 100
patch_size: ???
context_length: ???