_target_: uni2ts.model.moirai.MoiraiForecast
module:
  _target_: uni2ts.model.moirai.MoiraiMoEModule.from_pretrained
  pretrained_model_name_or_path: Salesforce/moirai-moe-1.0-R-small
mode: autoregressive
num_samples: 100
patch_size: 16
context_length: ???