_target_: uni2ts.model.moirai_moe.MoiraiMoEForecast
module:
  _target_: uni2ts.model.moirai_moe.MoiraiMoEModule.from_pretrained
  pretrained_model_name_or_path: Salesforce/moirai-moe-1.0-R-small
num_samples: 100
patch_size: 16
context_length: ???