_target_: uni2ts.model.moirai.MoiraiPretrain
min_patches: 4
min_mask_ratio: 0.1
max_mask_ratio: 0.2
max_dim: 100
num_training_steps: 10000
num_warmup_steps: 1000
loss_func:
  _target_: uni2ts.loss.packed.PackedNLLLoss
val_metric:
  - _target_: uni2ts.loss.packed.PackedNLLLoss
  - _target_: uni2ts.loss.packed.PackedMSELoss
module_kwargs:
  distr_output:
    _target_: uni2ts.distribution.MixtureOutput
    components:
      - _target_: uni2ts.distribution.StudentTOutput
      - _target_: uni2ts.distribution.NormalOutput
  d_model: 768
  num_layers: 12
  patch_sizes: [16, 32, 64]
  max_seq_len: 512
  attn_dropout_p: 0.1
  dropout_p: 0.1
  scaling: true
