# load a pretrained checkpoint from huggingface hub
_target_: uni2ts.model.moirai.MoiraiFinetune
module:    
  _target_: uni2ts.model.moirai.MoiraiModule.from_pretrained
  pretrained_model_name_or_path: Salesforce/moirai-1.1-R-base
module_kwargs:
  _target_: builtins.dict
  distr_output:
    _target_: uni2ts.distribution.MixtureOutput
    components:
      - _target_: uni2ts.distribution.StudentTOutput
      - _target_: uni2ts.distribution.NormalFixedScaleOutput
      - _target_: uni2ts.distribution.NegativeBinomialOutput
      - _target_: uni2ts.distribution.LogNormalOutput
  d_model: 768
  num_layers: 12
  patch_sizes: ${as_tuple:[8, 16, 32, 64, 128]}      
  max_seq_len: 512                        
  attn_dropout_p: 0.0
  dropout_p: 0.0
  scaling: true
min_patches: 2           
min_mask_ratio: 0.1      
max_mask_ratio: 0.4     
max_dim: 128     
loss_func:
  _target_: uni2ts.loss.packed.PackedNLLLoss
lr: 5e-8                              
weight_decay: 1e-1      
beta1: 0.9              
beta2: 0.98              

num_training_steps: 10000                
num_warmup_steps: 0