#_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
#checkpoint_path:
#  _target_: huggingface_hub.hf_hub_download
#  repo_id: Salesforce/moirai-1.0-R-small
#  filename: model.ckpt
#num_samples: 100
#patch_size: ???
#context_length: ???


_target_: uni2ts.model.llm_moirai.LlmMoiraiForecast
_args_:
  checkpoint_path: /home/eee/qzz/uni2ts/outputs_prompt/finetune/moirai_1.0_R_small/ettm1/example_run/checkpoints/epoch=7-step=160.ckpt
  num_samples: 100
  patch_size: 128
  context_length: 4000